#####   INTERNAL SETTINGS   #####
sounds:
  start: 'res/start-sound.mp3'
  pause: 'res/pause-sound.mp3'
states:
  WORK:
    color: '#ff9800'
    webhook: 'pomodoro-work'
  READY:
    color: '#e65100'
    webhook: 'pomodoro-work'
  PAUSE:
    color: '#1aa7ec'
    webhook: 'pomodoro-pause'
  DONE:
    color: '#4caf50'
    webhook: 'pomodoro-pause'
  STARTING:
    color: '#e65100'


# Firebase
FIREBASE_REF_TIME_DONE: 'APPDATA/pomodoro-windows/Arbeitszeit'
FIREBASE_REF_SETTINGS: 'APPDATA/pomodoro-windows/Settings'


# Ticktick
HABIT_NAME: 'Arbeiten'


#####   USER SETTINGS   #####

# POMODORO:
default_settings:
  work_timer_duration: 60
  pause_timer_duration: 15
  timer_step_size: 5
  daily_work_time_goal: 240
  features:
    Hide Windows: true
    Spotify: false
    # Spotify Bluetooth-Only: true
    Home Assistant: false
    Play Sound: true
    Habit Tracking: true

  VOLUME: 1


# SPOTIFY
work_playlist: 'spotify:playlist:6CCoTOqud9zrWmuOl3L7VK'
pause_playlist:  # 'spotify:playlist:4tCPOhgVlAFTtMSrT7T97j'
SPOTIFY:
  redirect_uri: "http://localhost:7787"
  scope: "user-read-playback-state user-modify-playback-state user-read-currently-playing"